### ISSUE TITLE
Window doesn't dissappear 

### ISSUE THREAD

**Issue by Mal-content** [MrMime71/PLHv2#1]
Clicking CLOSE not making the window go away, I'm guessing 7.3 broke things. 

Any chance on some fix? 

Thanks for making this amazing mod. 🥇

**Comment by MrMime71** [comment]
fixed now.. was the playsound error
Btw.. tnx for feedback.. i have no clue how many ppl download this fork..

nice to see its atleast 1 0o

**Comment by MrMime71** [comment]
updated to 1.32.. it not my addon.. Its madone of Zul'jin.. i just make frames to it :D

**Comment by Mal-content** [comment]
Thanks for looking into it :) 
I'm aware  that you only changed addon a bit. :) Still amazing job. 

Helps a lot with running alts in lfr etc. 
Don't get me wrong but im hoping it wont get too popular, coz blizzard have tendency to brake things that makes life easier!

**Comment by MrMime71** [comment]
If you want the version with the whisper button. I can send it

On 4 Sep 2017 7:18 pm, "Mal-content" <notifications@github.com> wrote:

Thanks for looking into it :)
I'm aware that you only changed addon a bit. :) Still amazing job.

Helps a lot with running alts in lfr etc.
Don't get me wrong but im hoping it wont get too popular, coz blizzard have
tendency to brake things that makes life easier!

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/MrMime71/PLHv2/issues/1#issuecomment-327004717>, or mute
the thread

**Comment by Mal-content** [comment]
Would love to <3 
Sorry for slow response was away ;)

**Comment by MrMime71** [comment]
I got whisperbutton?

On 7 Sep 2017 4:19 pm, "Mal-content" <notifications@github.com> wrote:

Would love to <3
Sorry for slow response was away ;)

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/MrMime71/PLHv2/issues/1#issuecomment-327813945>, or mute
the thread

**Comment by Mal-content** [comment]
What do you mean?

**Comment by MrMime71** [comment]
i meant .. do u have whisperbutton?

anyway.. here is the the current version i use: http://www.mediafire.com/file/moodzo3c7byyi04/PersonalLootHelperFrames070917-1.32.zip

**Comment by Mal-content** [comment]
Thanks this works! :) Previously i had whisper button but couldnt close the windo.

**Comment by MrMime71** [comment]
i saw i have a bug in when the name of the announce winner is appearing..

if it matters to you i can upload it

**Comment by Mal-content** [comment]
Would love to.
Are you planning on keeping the add-on up to date for next patch as well?
